# Generated by Django 4.1.2 on 2023-04-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonRatingsApp', '0003_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(default='description will be added soon', max_length=1000),
        ),
    ]
